// Same content as web — 2 free + 48 premium per platform
const s = (titleAr, bodyAr, titleEn, bodyEn) => ({ ar: { title: titleAr, body: bodyAr }, en: { title: titleEn, body: bodyEn } });

export const SECRETS = {
  instagram: {
    free: [
      s("أول 3 ثوان = كل شي", "خوارزمية Reels تقيس Retention في أول 3 ثوان.", "First 3 seconds = everything", "Reels measures retention in first 3 seconds."),
      s("النشر مرتين يومياً يقتل Reach", "Instagram يخفّض الحساب اللي ينشر أكثر من Reel واحد/24h.", "Posting 2x/day kills reach", "Instagram suppresses accounts posting 2+ Reels/24h."),
    ],
    premium: [
      s("Shares > Saves > Comments > Likes", "الخوارزمية تعطي Shares وزن أعلى بـ 5x.", "Shares weighted 5x", "Algorithm weighs shares 5x higher."),
      s("Loop المثالي = 7 ثوان", "Reels 7 ثوان تنتهي بنفس الفريم تحقق 3-5 replays.", "Perfect loop = 7s", "7s Reels ending on start frame = 3-5 replays."),
      s("Caption أول 125 حرف", "فقط أول 125 حرف تظهر قبل 'more'.", "First 125-char caption", "Only first 125 chars show before 'more'."),
      s("5 هاشتاقات > 30", "3-5 هاشتاقات نيش تتفوق على 30 generic.", "5 hashtags > 30", "3-5 niche tags beat 30 generic."),
      s("Trending Audio 48 ساعة", "نافذة ذهبية أول 48 ساعة من ظهور الصوت.", "48h golden audio window", "Sounds: 48h golden window."),
      s("CTA في الكابشن لا الفيديو", "Reels فيها 'Follow me' منطوقة تقل Reach.", "CTA in caption", "Spoken 'follow me' drops reach."),
      s("9:16 صارم", "أي black bars = TikTok repost = -60% Reach.", "Strict 9:16", "Black bars = TikTok repost = -60%."),
      s("DM Shares = الذهب", "مشاركة DM = أقوى signal للخوارزمية.", "DM shares = gold", "DM share = strongest algorithm signal."),
      s("Pin أول 3 Reels", "Pin أقوى 3 Reels على البروفايل = first impression.", "Pin top 3 Reels", "Pinning top 3 = first-impression bait."),
      s("Reply في أول ساعة", "كل reply في أول ساعة = boost للـ Reel.", "Reply in 1st hour", "Each 1st-hour reply boosts the Reel."),
      s("3-5 Stories متتابعة", "ترفع زيارات البروفايل 200%.", "3-5 stories burst", "Raises profile visits 200%."),
      s("Reach بدل Views", "Non-followers % > 70% = الـ Reel فيرال.", "Track Reach not Views", "Non-followers >70% = viral."),
      s("Carousel = 10 صفحات", "Sweet spot يجعل المستخدم يرجع 2-3 مرات.", "Carousel = 10 slides", "Sweet spot returns users 2-3x."),
      s("Geo-Tag مدينة كبيرة", "دبي/رياض/القاهرة يفتح Local Discovery.", "Geo-tag major city", "Dubai/Riyadh/Cairo opens Local Discovery."),
      s("Collab Posts = 2x Reach", "Collab يظهر على feed الحسابين.", "Collab posts 2x reach", "Collab surfaces in both audiences' feeds."),
      s("تجنّب Reels < 6s", "أقل من 6 ثوان = spam flag.", "Avoid Reels <6s", "Under 6s = spam flag."),
      s("Post 7-9am أو 7-10pm", "Window MENA. تجنّب الظهر و2-5am.", "Post 7-9am/7-10pm", "MENA window. Avoid noon and 2-5am."),
      s("Hook في أول Carousel", "أول صفحة = العنوان اللي يقرر التمرير.", "First slide = hook", "Slide 1 decides scroll."),
      s("Highlights مرتبة بمواضيع", "+40% Profile Visits بـ Highlights themed.", "Themed Highlights", "Themed Highlights = +40% profile visits."),
      s("Caption ينتهي بسؤال", "Reply Rate +65%.", "Question-end caption", "Reply rate +65%."),
      s("علّق على Reel نفسك", "خلال 10 دقائق بسؤال = ثريد فوري.", "Self-comment with Q", "Self-comment in 10 min = instant thread."),
      s("الموسيقى أعلى من -18dB", "تخفي الكلام. اضبط يدوياً.", "Music >-18dB drowns voice", "Adjust manually below -18dB."),
      s("'احفظ هذا' > 'تابعني'", "Saves CTA يتفوّق 2x.", "'Save this' 2x", "'Save this' beats 'follow' 2x."),
      s("الفريم الأول مشرق", "RGB > 150 = +30% Reach.", "Bright first frame", "RGB >150 first frame = +30% reach."),
      s("رابط واحد في البايو", "12% CTR. أربعة روابط = 3%.", "1 link in bio", "1 link = 12% CTR. 4 links = 3%."),
      s("Stitch Reel ناجح بنفسك", "Reel جديد على القديم = double boost.", "Stitch your hits", "Stitch new on old = double boost."),
      s("هاشتاقات في أول كومنت", "نفس signal، كابشن أنظف.", "Tags in 1st comment", "Same signal, cleaner caption."),
      s("Cross-share لـ Facebook", "Recommend on Facebook = +40% Reach.", "Cross-share to FB", "+40% free reach."),
      s("Subtitle: عريض + ظل", "Sans-serif مع shadow أسود.", "Bold sans + shadow", "Bold sans-serif + black shadow."),
      s("Trending Sound من نيشك فقط", "خارج نيشك = موت Reel.", "Niche sound only", "Out-of-niche sound = dead Reel."),
      s("وجه في Cover", "Reels بوجه = 2x Watch Time.", "Face in cover", "Face = 2x watch time."),
      s("لا روابط خارجية 90 يوم", "حساب جديد + روابط = Reach limit.", "No external links 90d", "New + links = reach limit."),
      s("Tag براند كبير", "ممكن يزور أو يعيد share.", "Tag big brands", "May trigger visit/repost."),
      s("Story Poll = 4x Reply", "Poll Sticker يضاعف التفاعل 4x.", "Poll = 4x reply", "Poll sticker = 4x replies."),
      s("Creator > Business", "Business account: -8% organic reach.", "Use Creator account", "Business: -8% organic reach."),
      s("DM بعد follow", "Welcome DM = 3x engagement rate.", "DM after follow", "Welcome DM = 3x ER."),
      s("Emoji واحد فقط", "أكثر = -18% Reach.", "1 emoji only", "More = -18% reach."),
      s("افحص Top 3 Reels أسبوعياً", "كرّر formula الـ Replays.", "Audit weekly top 3", "Repeat replay formula."),
      s("Reels في Highlights", "Highlight 'Best of' = evergreen reach.", "Reels in Highlights", "'Best of' Highlight = evergreen."),
      s("Niche Lock 30 يوم", "موضوع واحد فقط في أول 30 يوم.", "30-day niche lock", "First 30 days: 1 niche."),
      s("Meta Business Suite OK", "الجدولة بدون عقوبة (myth قديم).", "Scheduling = no penalty", "Scheduling penalty is a myth."),
      s("Re-share في Story 24h", "Reel ناجح بعد 24h = second boost.", "Re-share after 24h", "Hit Reel after 24h = 2nd boost."),
      s("أخفِ عدّاد الـ Likes", "تركز على Saves = algorithm reward.", "Hide likes", "Focus shifts to saves."),
      s("Sticker في كل Story", "Poll/Quiz/Question = +60% completion.", "Sticker every story", "+60% completion."),
      s("Pin أول تعليق ذكي", "يحدد tone للثريد كامل.", "Pin smart 1st comment", "Sets the thread tone."),
      s("Tag صاحب الـ Audio", "ممكن يعيد share = 2x Reach.", "Tag audio creator", "May share = 2x reach."),
      s("Cover من Canva", "Big text + face = +25% click.", "Canva cover", "Big text + face = +25% click."),
      s("لا Boost في أول 30 يوم", "يفسد organic graph.", "No Boost 30d", "Boost corrupts organic graph."),
    ],
  },
  tiktok: {
    free: [
      s("يختبر على 200 شخص أولاً", "Watch Time < 80% هنا = فيديو ميت.", "Tests on 200 first", "Watch Time <80% = dead."),
      s("Watch Time > Completion", "60s مشاهد 45s > 15s كامل 100%.", "Watch Time > Completion", "60s watched 45s beats 15s 100%."),
    ],
    premium: [
      s("FYP من Tribe لا Followers", "Niche واضح > Followers كثيرون.", "FYP from Tribe", "Clear niche > many followers."),
      s("3-Strikes Rule", "3 فلوبس = 7 أيام تبريد.", "3-Strikes Rule", "3 flops = 7-day cool-down."),
      s("Hook ثلاثي", "نص + نطق + visual motion معاً.", "Triple hook stack", "Text + voice + visual motion."),
      s("تعليقك أنت = signal", "خلال 10 دقائق بسؤال.", "Self-comment signal", "In 10 min with a question."),
      s("Sound Match جوهري", "trending داخل نيشك فقط.", "Niche sound only", "Trending in YOUR niche only."),
      s("Captions < 50 حرف", "Hook فقط، لا story.", "Captions <50 chars", "Hook only, no story."),
      s("9-15s Goldilocks", "أعلى Replay Rate.", "9-15s sweet spot", "Highest replay rate."),
      s("لا Watermarks", "CapCut/InShot = shadow ban خفيف.", "No watermarks", "CapCut/InShot = soft ban."),
      s("Live 30 دقيقة", "يحيي كل الفيديوهات القديمة 24h.", "30-min Live", "Revives old videos 24h."),
      s("Stitch + Duet", "يدخلك في feed المنشئ الأصلي.", "Stitch + Duet", "Enter original creator's feed."),
      s("Burned Captions", "+15% Watch Time على auto-CC.", "Burned-in subs", "+15% WT over auto-CC."),
      s("5-7am Lull Hours", "MENA: supply قليل = boost.", "5-7am MENA", "Low supply window."),
      s("Series Feature", "افتح Series على فيديو ناجح.", "Series for followers", "Open Series on a winner."),
      s("3+ هاشتاقات spam", "1 كبير + 1 نيش فقط.", "Max 3 hashtags", "1 big + 1 niche only."),
      s("Edit Style ثابت", "تغيير = موت النمو.", "Consistent edits", "Switching kills growth."),
      s("Profile Click 5x", "أقوى من Like بـ 5x.", "Profile click 5x like", "Profile click 5x stronger."),
      s("Shadowban نادر", "الفلوبس = ضعف hook.", "Shadowban rare", "Flops = weak hooks."),
      s("#fyp لا يفيد", "TikTok يتجاهله منذ 2023.", "#fyp ignored", "Ignored since 2023."),
      s("Video Reply = 4x Reach", "ارد بفيديو على تعليق.", "Video reply 4x", "Reply with video."),
      s("لا تحذف الفلوبس", "تصب signals مفيدة.", "Don't delete flops", "Feed useful signals."),
      s("Custom Thumb 2x", "اختر thumbnail يدوي.", "Manual thumb 2x", "Manual thumb 2x profile click."),
      s("1080×1920 60fps", "60fps يحصل boost.", "1080×1920 60fps", "60fps gets boost."),
      s("Auto-CC ضعيف للعربي", "30% errors. burned فقط.", "Auto-CC weak Arabic", "30% errors. Burn in."),
      s("POV = 80%+ Retention", "Immersion يرفع Retention.", "POV 80%+ retention", "Immersion lifts retention."),
      s("Allow Downloads", "repost مجاني يرفع reach.", "Allow downloads", "Free reposts boost reach."),
      s("TikTok Shopping -25%", "تفعيلها يخفض Reach 25%.", "Shopping -25%", "Enabling Shopping cuts organic 25%."),
      s("Followers tab يموت", "FYP فقط. <12% تستعمل tab.", "Followers tab dying", "<12% use Followers tab."),
      s("4am نافذة سرية", "Supply ينخفض جداً.", "4am secret", "Supply drops massively."),
      s("Age 2 أسابيع قبل أول post", "Cold start أفضل.", "Age account 2w", "Better cold start."),
      s("لا Stitch-only", "80% أصلي على الأقل.", "Avoid Stitch-only", "Be 80% original."),
      s("Trend + Original", "trend مع منسوخ = موت.", "Trend + original", "Trend + copy = death."),
      s("1 فيديو/يوم Cold Start", "أفضل training للخوارزمية.", "1/day cold start", "Best algorithm training."),
      s("Niche Lock 30 يوم", "موضوع واحد فقط.", "30-day niche", "1 topic only first 30 days."),
      s("Cover = first 0.1s", "اضبط أول فريم.", "Cover first 0.1s", "Tune first frame."),
      s("Wait for it + Pin", "Watch Time × 2.", "'Wait for it' pinned", "2x watch time."),
      s("CapCut Watermark -25%", "TikTok يكتشفه.", "CapCut -25%", "TikTok detects it."),
      s("AR Effects Boost", "TikTok يدفع Effects.", "AR Effects boost", "Effects library push."),
      s("لا تغير avatar أول 14 يوم", "soft ban خفيف.", "No avatar 14d", "Soft ban risk."),
      s("Pin أعلى 3 فيديوهات", "first impression بait.", "Pin top 3", "First-impression bait."),
      s("Voice-Over 3x", "أفضل من text-only.", "Voice-over 3x", "Beats text-only 3x."),
      s("Q&A Pinned Comment", "ثريد طويل = love.", "Q&A pinned", "Long thread = love."),
      s("Reuse Flop Audio", "ممكن ينجح في context ثاني.", "Reuse audio", "May win with new context."),
      s("Live في prime time", "Discovery Live tab.", "Live prime time", "Discovery Live boost."),
      s("Trends خلال 7 أيام", "بعدها saturated.", "Trends 7 days", "After: saturated."),
      s("Topic في 0.5s", "أعلن بصرياً مبكراً.", "Topic in 0.5s", "Announce early."),
      s("لا Black Bars", "-40% Reach.", "No black bars", "-40% reach."),
      s("Loop Question End", "Replay مضمون.", "Loop question end", "Guaranteed replay."),
      s("Now Tab Consistency", "نفس slot يومياً.", "Now Tab daily", "Same slot daily."),
      s("Skip Bot Comments", "تربك training.", "Skip bots", "They confuse training."),
    ],
  },
  shorts: {
    free: [
      s("خوارزمية منفصلة", "feed مستقل عن YouTube الطويل.", "Separate algorithm", "Separate from long-form."),
      s("Loop لا Completion", "Replays = signal خرافي.", "Loop not completion", "Replays = monster signal."),
    ],
    premium: [
      s("Shorts Shelf على Home", "views إضافية أيام.", "Shorts Shelf home", "Days of extra views."),
      s("60s vs 15s", "60s = أعلى RPM.", "60s vs 15s", "60s = higher RPM."),
      s("In-video Subscribe", "8x Conversion.", "In-video subscribe", "8x conversion."),
      s("سؤال في Title", "+22% CTR.", "Question title", "+22% CTR."),
      s("Pin Comment", "Engagement signal دائم.", "Pin comment", "Lasting engagement."),
      s("Thumbnail لا يهم في feed", "ركّز على أول فريم.", "Thumb irrelevant feed", "First frame matters."),
      s("Description + 3 hashtags", "يساعد التصنيف.", "Description + 3 tags", "Helps classification."),
      s("Link Short لـ Long Video", "Related Video funnel.", "Link Short to long", "Funnel via Related."),
      s("Voice On Boost", "أفضل من music-only.", "Voice on", "Beats music-only."),
      s("1-2 Shorts/يوم", "أكثر = momentum مقسّم.", "1-2/day", "More splits momentum."),
      s("AVD > 90%", "أقل = distribution يقف.", "AVD >90%", "Less = distribution stops."),
      s("Watch Next End Card", "Session Time × 3.", "Watch Next", "3x session time."),
      s("Bilingual Captions", "MENA reach × 2.", "Bilingual captions", "2x MENA reach."),
      s("Heart Top Comments", "algorithm يعتبره core.", "Heart top comments", "Marks them core."),
      s("Series Playlists", "Watch Time × 2.5.", "Series playlists", "2.5x watch time."),
      s("Re-upload بعد 60 يوم", "بـ caption مختلف.", "Re-upload 60d", "Different caption."),
      s("Low RPM، Sponsors", "1M views = $1000+ deals.", "Low RPM, sponsors", "1M views = $1000+ deals."),
      s("Shorts ≥ 30s AdSense", "مؤهل لـ monetization.", "30s+ AdSense", "Monetization eligible."),
      s("#shorts في Title", "تصنيف أسرع.", "#shorts in title", "Faster classification."),
      s("Logo في كورنر", "+35% Brand Recall.", "Corner logo", "+35% recall."),
      s("Community Tab Repost", "بعد 7 أيام = second boost.", "Community repost", "After 7d = 2nd boost."),
      s("Stories Pre-launch", "teaser قبل الإطلاق.", "Stories teaser", "Pre-launch hype."),
      s("Shelf في 60 ثانية", "Golden window.", "Shelf in 60s", "Golden window."),
      s("CTR > 8% Boost", "تحت 5% = موت.", "CTR >8%", "Under 5% dies."),
      s("YouTube Music Library", "Copyright-safe + Boost.", "YT Music Library", "Safe + boost."),
      s("Thumb مهم في Browse", "ليس feed.", "Thumb in Browse", "Not in feed."),
      s("لا تكتب 'Shorts'", "YouTube spam flag.", "Don't say 'Shorts'", "Spam flag."),
      s("لا End Screens", "آخر ثانية للـ self-promo.", "No end screens", "Last sec self-promo."),
      s("لا Hard Cuts 1.5s", "العين تشتت.", "No cuts 1.5s", "Scatters the eye."),
      s("1080×1920 9:16 ≤60s", "off-spec = downgraded.", "Spec strict", "Off-spec downgraded."),
      s("Pin timestamp link", "لفيديو طويل.", "Pin long-video link", "To your long video."),
      s("Live Boost Shorts", "live يدفع Shorts للـ subs.", "Live boosts Shorts", "Live pushes Shorts to subs."),
      s("Pinned Playlist", "channel home pre-shows.", "Pinned playlist", "Home pre-shows."),
      s("No TikTok Reposts", "watermark = -50% Reach.", "No TikTok reposts", "Watermark = -50%."),
      s("3+/يوم يقتل momentum", "Stop عند 3.", "Stop at 3/day", "Splits momentum."),
      s("30-50s Monetization", "Best Watch Time + AdSense.", "30-50s sweet spot", "Best WT + AdSense."),
      s("YT Shorts Editor", "بدون watermark + boost.", "YT Editor", "No watermark + boost."),
      s("Chapters في Description", "SEO boost حتى لـ 60s.", "Chapters even 60s", "SEO boost."),
      s("Membership Badges", "Social proof في comments.", "Member badges", "Social proof."),
      s("Pin Short في Long Video", "ناجح = traffic مجاني.", "Pin Short long", "Free traffic."),
      s("Engagement Burst 10 min", "أول 10 دقائق = success.", "10-min burst", "First 10 min predict."),
      s("Remix Feature", "ركوب viral قانونياً.", "Use Remix", "Legal viral ride."),
      s("شاهد المنافسين 100%", "تدريب الخوارزمية.", "Watch competitors", "Train algorithm."),
      s("احذف Shorts الفاشلة 7 أيام", "تخفض Feed.", "Delete flops 7d", "Drags feed down."),
      s("Shorts Fund → AdSense", "30s+ مؤهل.", "Fund → AdSense", "30s+ eligible."),
      s("Long Video Pin Promo", "Pin link Short.", "Long-video pin promo", "Pin Short link."),
      s("Burned Subs > Auto-CC", "+20% Watch Time.", "Burned > auto-CC", "+20% WT."),
      s("Member Funnel from Shorts", "3-5% conversion ممكن.", "Members from Shorts", "3-5% possible."),
    ],
  },
};

export function getISOWeek(d = new Date()) {
  const date = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()));
  const dayNum = date.getUTCDay() || 7;
  date.setUTCDate(date.getUTCDate() + 4 - dayNum);
  const yearStart = new Date(Date.UTC(date.getUTCFullYear(), 0, 1));
  return Math.ceil((((date - yearStart) / 86400000) + 1) / 7);
}

export function seededShuffle(arr, seed) {
  const a = [...arr];
  let st = seed * 9301 + 49297;
  for (let i = a.length - 1; i > 0; i--) {
    st = (st * 9301 + 49297) % 233280;
    const j = Math.floor((st / 233280) * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
